group: travis_latest
dist: bionic
sudo: true

env:
    global:
        # prefix before commands - used for wine, there the prefix is "wine"
        - cPREFIX=""
        # command to launch python interpreter (its different on macOs, there we need python3)
        - cPYTHON="python"
        # command to launch pip (its different on macOs, there we need pip3)
        - cPIP="python -m pip"
        # switch off wine fix me messages
        - WINEDEBUG=fixme-all
        # mypy path
        - MYPYPATH="./pct_python_default_test/3rd_party_stubs"
        # package name
        - PACKAGE_NAME="pct_python_default_test"
        # the registered CLI Command
        - CLI_COMMAND="pct_python_default_test"
        # the source file for rst_include (rebuild rst file includes)
        - RST_INCLUDE_SOURCE="./.docs/README_template.rst"
        # the target file for rst_include (rebuild rst file includes)
        - RST_INCLUDE_TARGET="./README.rst"
        # secure environment variable
        - secure: "iNUhR4KCJWa3rfa9fQPjRRZPi3/BQFsQooxhlhb58hzYHK50vPxWYoUakdFG4ebP6I8H+2VNQq+hdc/67MTOrRt9DXlv/8SsbfyiEXpPmdaJ1v1Oi8DFJo6P9Xxj9l9/i9k+X3cT1z+ZjTnQ7Q6BNma8vgqjrHs+bIEcZbxeQnuG3Tr5jMPXhlciFSN5zsRUjOhe5gckRNauFG3cczpvOxRjIjTTrI1hgf3GDtirINrSZHZwmS9XheaXo9ml7jYzTikTSBbKJNS52cd1ViFzMhr1GcmcdVjhIfEs3n9arIfB4S+ScAFDXU2ekRjdlzYCh6ixFVQqlBUKsuZjnrO0Te/cuxDXerag8eTNC0kGKRy13bOxTNNhWbmO4YAoCLkx0a4yM5+GMHxaf9+08KkAogYTqlYn6i+34UNQ3/EIeJfCl/GTnZRfZ4WdGw9qAgZ60Fnx9TDVx9GBsfUgjk+Z32WZMyPsR7fpFO79h98gOtTFZ35Q4mF/9XNeVRf/IPPaIv74t9DYs026Jx/ip9k0UE7i914DR/KM7bfutp9oPBX7KinG419NojlvI92Kl/RqJHrMOom1pi/KskOHIklgvo9Pq4gYgTYEV/P/qwHRhq+q9mVHJmk5j1xyCgcAB+J+PFFzefiHlybZgIEawYV2vCj7iPTDCvyrCcOsq+Lz97w="  # CC_TEST_REPORTER_ID.secret
        - secure: "HN5UX5qhuVm2H9ahzNzfQ1mZhGWJTEmOb55RquDY3cLuKeO487ylqWaGTftjlMm3dopJljRsgTPQSWTT9sxwRGXje6qeQTSQ5xjQBCyk7wz8azV4YpsLMDGnUldtG/CVuaJ1ujDlA3r1M3H2vY5bZWt90+4Hu0dILzTYPyAhg+MrLIm9mSB1SLP9H0SDXNp5JM8j1zf/2eF0prXYd6safPBKUnuPcGcGIGsGX97ban39gfZc6PReqY43tLY9WuM2OdLATCxz1wqDsIGgqqF0qWqLqql7S+Th04w03GH2di9SxHDPs7mP54dYY7UyK341acuVJhZ/UlBroK6iMKG3AA6j9oVZ81vpqalMDgPKUiOUas2RXpzSwDUwAqbtk7WxuNEHWNa+4yJITeddqIwOaQrbf7+m58XTBU/9opBWb58ORx6lBvWRMgPSPYqVwRNIxmEXoMC4wYNiu3m3DJ28thoKBo1cFrHPVUG4fDhhuWdB2nC2vY5SZoYDIrr7znwom8MGju6VBDUkFRNg6ZjN26EiS8j32iy1ZSg+tNM7AUTefdlMSALsEleQqDDQeAquAw6Opb8F8qfyH33BdZ3dypjqcDg456OVR8UCs3zJi9y7OSDRyNh+AplHck0PZiWujpUMNUiYnNH9M4DQe59qtzf1hF1n4rszuFmRdc58SH8="  # PYPI_PASSWORD.secret


addons:
  apt:
    packages:
    - xvfb      # install xvfb virtual framebuffer - this we need for WINE
    - winbind   # needed for WINE

services:
- xvfb          # is needed for WINE on headless installation
- docker        # for cibuildwheel

language:
- python

python:
- 3.6
- 3.7
- 3.8
- 3.8-dev
- pypy3


arch:
- amd64
- ppc64le
- s390x
- arm64

os: 
- windows
- linux
- osx

jobs:
  exclude:
  - os: windows
    arch: ppc64le
    arch: s390x
    arch: arm64
  - os: osx
    arch: ppc64le
    arch: s390x
    arch: arm64
  include:
  - stage: deploy
    arch: amd64
    os: linux
    python: 3.8
    script: echo "here we are"


notifications:
  email:
    recipients:
        - bitranox@gmail.com
    # on_success default: change
    on_success: never
    on_failure: always
